services:
  - type: web
    name: context7-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    
    # Pour servir le port dynamique imposé par Render
    # Express écoute déjà sur process.env.PORT dans server.js
    healthCheckPath: /healthz
    routes:
      - type: rewrite
        source: /.well-known/openapi.yaml
        destination: /.well-known/openapi.yaml
